### ISSUE TITLE
'make' failing on mac os 10.14.3

### ISSUE THREAD

**Issue by Zacharias030** [tomasmcz/imago#10]
```
cd imago
make
```

outputs

```
gcc -Ofast -fPIC -shared -I/usr/include/python2.7/ pcf.c -lpython2.7 -o src/pcf.so
pcf.c:1:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^~~~~~~~~~
1 error generated.
make: *** [src/pcf.so] Error 1
```

I have python installed with homebrew in addition to the system python (if that matters)

**Comment by Zacharias030** [comment]
cf. https://github.com/neuronsimulator/nrn/issues/50

line should be:
`#include <Python/Python.h>`

**Comment by tomasmcz** [comment]
Your line does not work on my Ubuntu installation. I don't know if there is any universal solution or which of these is correct.
